repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace         # Mandatory Hook 1
    -   id: end-of-file-fixer           # Mandatory Hook 2
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets              # Mandatory Hook 3

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix]
